//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentskaSluzba2.App_Start
{
    using System;
    using System.Collections.Generic;
    
    public partial class Godina_Studij
    {
        public int ID_Godina_Studij { get; set; }
        public int ID_Godina { get; set; }
        public int ID_Studij { get; set; }
    
        public virtual Studij Studij { get; set; }
        public virtual Godina_Studij Godina_Studij1 { get; set; }
        public virtual Godina_Studij Godina_Studij2 { get; set; }
        public virtual Godina_Studij Godina_Studij11 { get; set; }
        public virtual Godina_Studij Godina_Studij3 { get; set; }
    }
}
