//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentskaSluzba2.App_Start
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Studentska_sluzbaEntities : DbContext
    {
        public Studentska_sluzbaEntities()
            : base("name=Studentska_sluzbaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Godina> Godina { get; set; }
        public virtual DbSet<Godina_Studij> Godina_Studij { get; set; }
        public virtual DbSet<Plan_i_program> Plan_i_program { get; set; }
        public virtual DbSet<Predmet> Predmet { get; set; }
        public virtual DbSet<Predmet_Hijerarhija> Predmet_Hijerarhija { get; set; }
        public virtual DbSet<Prijava> Prijava { get; set; }
        public virtual DbSet<Profesor> Profesor { get; set; }
        public virtual DbSet<Smjer> Smjer { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<Student_tip> Student_tip { get; set; }
        public virtual DbSet<Studij> Studij { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Tip_Nastave> Tip_Nastave { get; set; }
        public virtual DbSet<Tipovi_studenata> Tipovi_studenata { get; set; }
        public virtual DbSet<Potvrda_pripadnosti> Potvrda_pripadnosti { get; set; }
        public virtual DbSet<Pohadjanje> Pohadjanje { get; set; }
        public virtual DbSet<Zalba> Zalba { get; set; }
        public virtual DbSet<v_Student> v_Student { get; set; }
        public virtual DbSet<v_Profesor> v_Profesor { get; set; }
        public virtual DbSet<v_Pohadjanje> v_Pohadjanje { get; set; }
        public virtual DbSet<Izborni> Izborni { get; set; }
        public virtual DbSet<Izborni_predmet> Izborni_predmet { get; set; }
    }
}
