//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentskaSluzba2.App_Start
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pohadjanje
    {
        public int ID_Pohadjanje { get; set; }
        public Nullable<int> ID_Student { get; set; }
        public Nullable<int> ID_profesor { get; set; }
        public Nullable<int> ID_plan_i_program { get; set; }
        public System.DateTime Datum { get; set; }
    
        public virtual Plan_i_program Plan_i_program { get; set; }
        public virtual Profesor Profesor { get; set; }
        public virtual Student Student { get; set; }
    }
}
