//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentskaSluzba2.App_Start
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipovi_studenata
    {
        public int ID_Tipovi_studenata { get; set; }
        public Nullable<int> ID_student { get; set; }
        public Nullable<int> ID_Student_tip { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Student_tip Student_tip { get; set; }
    }
}
