//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentskaSluzba2.App_Start
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Pohadjanje
    {
        public string Student { get; set; }
        public string Profesor { get; set; }
        public string Predmet { get; set; }
        public Nullable<int> Akademska_godina { get; set; }
    }
}
